### PR TITLE
Add some types

### PR DESCRIPTION
**Pull request by nf-s**
I have added more type definitions - mainly for symbolizers and attributes. (with a bit in `json_style`)

The goal was to remove all use of `any` from `attribute.ts` and `symbolizer.ts`.

### CODE REVIEW

**Comment by nf-s** [comment]
Yeah I'm not really sure of a good solution, because if you have to start checking whether these `get` functions have `(z)` or `(z, f)` - it will make those "composite" attributes quite complicated - for example `FontAttr` which has 5 `AttrOption` properties. How would we deal with a mix of per feature and per zoom level only functions?

```ts
export interface FontAttrOptions {
  font?: AttrOption<string>;
  fontFamily?: AttrOption<string>;
  fontSize?: AttrOption<number>;
  fontWeight?: AttrOption<number>;
  fontStyle?: AttrOption<string>;
}
```

I am leaning toward forcing everything to be `(z, f?)` for simplicity, but I'm not sure of performance implications of having to check `f?.properties?.someProp` instead of `f.properties.someProp`

**Comment by nf-s** [comment]
An idea for types:

```ts

export type AttrPerFeatureFunction<T> = (z: number, f: Feature) => T;
export type AttrStaticFunction<T> = (z: number) => T;
export interface Attr<T> {
  readonly per_feature: boolean;
  get: AttrStaticFunction<T> | AttrPerFeatureFunction<T>
}

export function isPerFeatureAttr<T>(attr: Attr<T>): attr is Attr<T> & {
  get: AttrPerFeatureFunction<T>;
} {
  return attr.per_feature;
}

export function isStaticAttr<T>(attr: Attr<T>): attr is Attr<T> & {
  get: AttrStaticFunction<T>;
} {
  return !attr.per_feature;
}

function test() {
  const someString = new StringAttr((z, f) => "some-value", "default-value");

  if (isStaticAttr(someString)) {
    someString.get(1);
  }

  if (isPerFeatureAttr(someString)) {
    someString.get(1, {} as any);
  }
}
```

**Comment by bdon** [comment]
@nf-s I think the PR as is is good-to-merge, is that OK? We can address cleaning up the API with (z) | (z,f) in a follow up.

**Comment by bdon** [comment]
nvm, let's move further discussion on type improvements to here: https://github.com/protomaps/protomaps.js/issues/61

Thanks for the PR, closing this one for now!

**Pull request merged**
